### PR TITLE
Add support for I18n without Rails

### LINKED ISSUE #20: I18n support
Any plans for I18n support? dry-validations works with I18n

### PR DESCRIPTION
**Pull request by noelrocha**
This add support for I18n, respecting dry-validation configurations

Closes #20

### CODE REVIEW

**Comment by michaelherold** [comment]
It looks like there's more to this. I would like to not _require_ I18n for this library, yet allow you to use it if you want.

**Comment by noelrocha** [comment]
Whats your suggestion? 

A global config like: 
```
Interactor::Contracts.configure do |config|
  config.messages = :i18n
end
```

**Comment by michaelherold** [comment]
Probably something more like:

```ruby
class MyInteractor
  include Interactor
  include Interactor::Contracts[messages: :i18n]
end
```

That safely loads I18n and displays a helpful error when I18n is not installed. Right now, as you can see, it fails with a bad error message and breaks the entire test suite. This will likely need a separate integration spec.

**Comment by michaelherold** [comment]
Due to the recent update to dry-validation 1.0, this is no longer compatible with the implementation for the gem so we'll have to rework it.

**Pull request closed without merging**
